# Generated by Django 4.2.13 on 2024-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_name_iha_isim_rename_available_iha_mevcut_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
            ],
        ),
    ]
