# Generated by Django 4.2.13 on 2024-06-26 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_customer_list_iha"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="customer_list",
            new_name="Customer",
        ),
    ]
